const attackTable = {
    2: "Jab 1",
    3: "Jab 2",
    4: "Jab 3",
    5: "Rapid Jabs",
    6: "Dash Attack",
    7: "FTilt",
    8: "UTilt",
    9: "DTilt",
    10: "FSmash",
    11: "USmash",
    12: "DSmash",
    13: "Nair",
    14: "Fair",
    15: "Bair",
    16: "Uair",
    17: "Dair",
    18: "Neutral Special",
    19: "Side Special",
    20: "Up Special",
    21: "Down Special",
    50: "Get Up Attack (Back)",
    51: "Get Up Attack (Front)",
    52: "Pummel",
    53: "FThrow",
    54: "BThrow",
    55: "UThrow",
    56: "DThrow",
    57: "Cargo FThrow",
    58: "Cargo BThrow",
    59: "Cargo UThrow",
    60: "Cargo DThrow",
    61: "Ledge Get Up Attack 100%+",
    62: "Ledge Get Up Attack",
    63: "Beam Sword Jab",
    64: "Beam Sword Tilt Swing",
    65: "Beam Sword Smash Swing",
    66: "Beam Sword Dash Swing",
};

module.exports = attackTable;